### PR TITLE
Add new `Merch` marker and pin type

### PR DESCRIPTION
**Pull request by sassypocoyo**
As suggested by @feliciofilipe, I created a new `Merch` pin that allows for a better distinction between types. Now, photos where the authors are showing of their style with the CeSIUM merch will be labeled with the **Merch** type, and the **Picture** type will be reserved for any photo of the trip the user might want to share with the CeSIUM family.

Also converted the marker icons to .svg format.

### CODE REVIEW

**Comment by nelsonmestevao** [comment]
Why are you adding two versions of the same image?

e.g. `public/images/markers/leader.svg` and `public/images/markers/leader-image.svg`?

**Comment by sassypocoyo** [comment]
> Why are you adding two versions of the same image?
> 
> e.g. `public/images/markers/leader.svg` and `public/images/markers/leader-image.svg`?

There were already two versions of the same image, not sure if you remember. One is for the map pins, because they need to be centered by the tip of the pin, explaining why they have the double of the height. The others are meant to be used normally on the Sidebar.

**Review by nelsonmestevao — APPROVED** [review]
Oh, I remember 👍

One day we should solve that somehow 😅

**Comment by sassypocoyo** [comment]
> Oh, I remember 👍
> 
> One day we should solve that somehow 😅

True, not sure how 😅

**Pull request merged**
